### ISSUE TITLE
Ctrl+ C 停止服务器时，导致文件破坏而无法重新启动

### ISSUE THREAD

**Issue by michaelmao999** [chubaostream/joyqueue#17]
com.jd.joyqueue.store.StoreInitializeException: java.io.IOException: 请求的操作无法在使用用户映射区域打开的文件上执行。
        at com.jd.joyqueue.store.PartitionGroupStoreManager.recover(PartitionGroupStoreManager.java:191) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.Store.restorePartitionGroup(Store.java:275) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.broker.store.StoreManager.doStart(StoreManager.java:82) ~[joyqueue-broker-core-4.1.0.jar:?]
        at com.jd.joyqueue.toolkit.service.Activity.start(Activity.java:55) ~[joyqueue-toolkit-4.1.0.jar:?]
        at com.jd.joyqueue.toolkit.service.Service.start(Service.java:39) ~[joyqueue-toolkit-4.1.0.jar:?]
        at com.jd.joyqueue.broker.BrokerService.startIfNecessary(BrokerService.java:380) ~[joyqueue-broker-core-4.1.0.jar:?]
        at com.jd.joyqueue.broker.BrokerService.doStart(BrokerService.java:320) ~[joyqueue-broker-core-4.1.0.jar:?]
        at com.jd.joyqueue.toolkit.service.Activity.start(Activity.java:55) ~[joyqueue-toolkit-4.1.0.jar:?]
        at com.jd.joyqueue.toolkit.service.Service.start(Service.java:39) ~[joyqueue-toolkit-4.1.0.jar:?]
        at com.jd.joyqueue.broker.Launcher.main(Launcher.java:33) [joyqueue-server-runtime-4.1.0.jar:?]
Caused by: java.io.IOException: 请求的操作无法在使用用户映射区域打开的文件上执行。
        at sun.nio.ch.FileDispatcherImpl.truncate0(Native Method) ~[?:1.8.0_202]
        at sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:97) ~[?:1.8.0_202]
        at sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:357) ~[?:1.8.0_202]
        at com.jd.joyqueue.store.file.StoreFileImpl.rollback(StoreFileImpl.java:375) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.file.PositioningStore.rollbackFiles(PositioningStore.java:175) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.file.PositioningStore.setRight(PositioningStore.java:135) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.PartitionGroupStoreManager$Partition.rollbackTo(PartitionGroupStoreManager.java:1383) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.PartitionGroupStoreManager$Partition.access$500(PartitionGroupStoreManager.java:1362) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.PartitionGroupStoreManager.recoverIndices(PartitionGroupStoreManager.java:199) ~[joyqueue-store-core-4.1.0.jar:?]
        at com.jd.joyqueue.store.PartitionGroupStoreManager.recover(PartitionGroupStoreManager.java:189) ~[joyqueue-store-core-4.1.0.jar:?]
        ... 9 more

**Comment by liyue2008** [comment]
请提供操作系统名称、版本，以及使用的什么文件系统？以便于我们进行测试。

**Comment by michaelmao999** [comment]
测试机器是widnows 10，NTFS，我正在linux下用最新代码尝试一下，稍后给你们反馈

**Comment by michaelmao999** [comment]
我使用最新的代码库，在Linux下面工作正常 CentOS Linux 7 (Core), Linux 3.10.0-957.el7.x86_64, XFS， 但是ZK总是报错：
  02:42:10:885] [main-SendThread(localhost:2181)] [WARN] - org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1162) - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_181]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_181]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) [zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
[02:42:11:006] [main-SendThread(localhost:2181)] [INFO] - org.apache.zookeeper.ClientCnxn$SendThread.logStartConnect(ClientCnxn.java:1032) - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
